### ISSUE TITLE
Callback URL?

### ISSUE THREAD

**Issue by ppfeufer** [jkey-67/spyglass#14]
From README.md

> CLIENTS_API_KEY = "-top-secret-api-key-"
>
> Register as developer and create a own application key on the [EVE-Developer](https://developers.eveonline.com/applications) webpage.

That requires a callback URL, what needs to be set here?

![image](https://user-images.githubusercontent.com/2989985/212762086-0dbc7781-d127-433a-9336-4f5547b84360.png)

**Comment by jkey-67** [comment]
http://localhost:8182/oauth-callback is used during registration process, but i added the clients api key to the repository.
